In [1]:
import ipywidgets
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
# %load cheb.py
from numpy import *
from numpy.fft import fft,ifft

def cheb(y):
    '''Chebyshev transform. Finds Chebyshev coefficients given y evaluated on
    Chebyshev grid'''
    N = len(y) - 1
    yt = real(fft(r_[y,y[-2:0:-1]]))
    yt = yt/(2*N)
    yt = r_[yt[0],yt[1:N]+yt[-1:N:-1],yt[N]]

    return yt

def icheb(c):
    '''Inverse Chebyshev transform. Evaluates Chebyshev series at the Chebyshev 
    grid points given Chebyshev coefficients.'''
    N = len(c) - 1
    y = r_[c[0],0.5*c[1:N],c[N],0.5*c[-1:N:-1]]
    y = y*2*N
    y = real(ifft(r_[y,y[-2:0:-1]]))[:N+1]

    return y


def Dcheb(y,interval):
    '''Chebyshev derivative of y evaluated on Chebyshev grid in interval [a,b]'''
    N = len(y) - 1
    a,b = interval
    x = 0.5*(b-a)*(cos(r_[0:N+1]*pi/N) + 1) + a

    k = r_[0:N]

    A = real(fft(r_[y,y[-2:0:-1]]))
    yy = real(ifft(1j*r_[k,0,-k[-1:0:-1]]*A))

    fact = 2.*(x-a)/(b-a)-1
    fact = fact[1:-1]
    yprime = -2./(b-a)*yy[1:N]/sqrt(1-fact**2)

    A = A/(2*N)
    A = r_[A[0],A[1:N]+A[-1:N:-1],A[N]]
    k = r_[0:N+1]

    yprime1 = sum(k**2*A)*2./(b-a)
    yprimeN = sum((-1)**(k+1)*k**2*A)*2./(b-a)

    return r_[yprime1,yprime,yprimeN]



def regrid(y,M):
    N = len(y) - 1
    a = cheb(y)
    if M==N:
        return y
    if M>N:
        a = r_[a,zeros(M-N)]
        return icheb(a)
    if M<N:
        a = a[:M+1]
        return icheb(a)



def clenshaw(x,c):
    '''Clenshaw algorithm to evaluate Chebyshev series at x
    assumes x is in [-1,1]'''
    N = len(c) - 1
    b = zeros(N+2)
    b[-1] = 0
    b[-2] = c[-1]
    for r in r_[N-1:0:-1]:
        b[r] = 2*x*b[r+1] - b[r+2] + c[r]
    s = x*b[1] - b[2] + c[0]

    return s


def clenshaw2(x,c,change_grid = True):
    '''Vectorized version of Clenshaw algorithm
    Use this for Chebyshev polynomial evaluation'''
    if change_grid:
    	if (min(x)!=-1) or (max(x)!=1):
        	x = 2*(x-min(x))/(max(x)-min(x)) - 1
    N = len(c) - 1
    b = zeros([N+2,len(x)])
    b[-1,:] = 0
    b[-2,:] = c[-1]
    for r in r_[N-1:0:-1]:
        b[r,:] = 2*x*b[r+1,:] - b[r+2,:] + c[r]
    s = x*b[1,:] - b[2,:] + c[0]

    return s



def chebD(c,interval):
    '''Finds derivative of Chebyshev series in spectral space
    i.e. maps c_n--->d_n where c_n,d_n are Chebyshev coefficients
    of f(x) and f'(x) in the interval [a,b].'''
    N = len(c) - 1
    a,b = interval
    if (a!=-1.) or (b!=1.):
        factor = 2./(b-a)
    else: 
        factor = 1.

    b = c*r_[0:N+1]


    cp = zeros_like(b)

    cp[0] = sum(b[1::2])

    evens = b[2::2]
    odds = b[1::2]

    cp[1:N+1-(N%2):2] = 2*cumsum(evens[-1::-1])[-1::-1]
    cp[2:N+1-((N+1)%2):2] = 2*cumsum(odds[-1::-1])[-2::-1]

    cp = cp*factor

    return cp


def chebD_semiinf(c):
    '''Finds the derivative of Chebyshev series in spectral space
    i.e. maps c_n --> d_n where c_n, d_n are Chebyshev coefficients
    of f(x) and f'(x) in the interval [0,oo)'''
    '''To be used only for the positive half-line'''
    
    N = len(c) - 1
    
    b = c*r_[0:N+1]


    cp = zeros_like(b)

    cp[0] = sum(b[1::2])

    evens = b[2::2]
    odds = b[1::2]

    cp[1:N+1-(N%2):2] = 2*cumsum(evens[-1::-1])[-1::-1]
    cp[2:N+1-((N+1)%2):2] = 2*cumsum(odds[-1::-1])[-2::-1]

    d0 = 3./4*cp[0] - cp[1]/2. + cp[2]/8.
    d1 = -cp[0] + 7./8*cp[1] - cp[2]/2. + cp[3]/8.
    d2 = cp[0]/4. - cp[1]/2. + 3./4*cp[2] - cp[3]/2. + cp[4]/8.
    d3 = cp[1]/8. - cp[2]/2. + 3./4*cp[3] - cp[4]/2. + cp[5]/8.
    
    dn = [ cp[i-2]/8. - cp[i-1]/2. + 3./4*cp[i] - cp[i+1]/2. + cp[i+2]/8.  for i in range(4,N-1)]

    dn1 = cp[N-1-2]/8. - cp[N-1-1]/2. + 3./4*cp[N-1] - cp[N-1+1]/2.
    
    dn2 = cp[N-2]/8. - cp[N-1]/2. + 3./4*cp[N]
    
    dn = r_[d0,d1,d2,d3,dn,dn1,dn2]

    return dn


def cheb2zD_semiinf(c):
    '''Finds the Chebyshev coefficients of the operator 2z df/dz when
    f has a series in Chebyshev rational functions Rn(z) = Tn((z-1)/(z+1)). Input
    is the coefficients of f.'''
    
    N = len(c) - 1
    
    b = c*r_[0:N+1]


    cp = zeros_like(b)

    cp[0] = sum(b[1::2])

    evens = b[2::2]
    odds = b[1::2]

    cp[1:N+1-(N%2):2] = 2*cumsum(evens[-1::-1])[-1::-1]
    cp[2:N+1-((N+1)%2):2] = 2*cumsum(odds[-1::-1])[-2::-1]

    d0 = -cp[2]/4. + cp[0]/2.
    d1 = cp[1]/4. - cp[3]/4.
    d2 = -cp[0]/2. + cp[2]/2. - cp[4]/4.
    
    dn = [ -cp[n-2]/4.  + cp[n]/2. - cp[n+2]/4 for n in range(3,N-1)] 
    
    dn1 = -cp[N-3]/4. + cp[N-1]/2
    dn2 = -cp[N-2]/4. + cp[N]/2
    
    dn = r_[d0,d1,d2,dn,dn1,dn2]
    
    return dn



def Intcheb(y,interval):
    '''Clenshaw-Curtis to find definite integral of function y(x) given at
    Chebyshev grid points in some interval [a,b]'''
    fact = 0.5*(interval[1]-interval[0])
    b = cheb(y)
    N = len(y) - 1
    if N%2 == 0:
        w = array([ 2./(-(2*k)**2+1) for k in r_[0:N/2+1]])
    else:
        w = array([ 2./(-(2*k)**2+1) for k in r_[0:(N-1)/2+1]])
    return dot(b[::2],w)*fact



def chebI(c,interval,x0=None,f0=None):
    if x0==None:
        x0=interval[0]

    N = len(c) - 1
    I = diag(1./(2*r_[0.5,r_[2:N+1]]),-1) -diag(1./(2*r_[1,r_[1:N]]),1)
    I[0,1] = 0
    
    factor = (interval[1]-interval[0])/2.
    
    ci = dot(I,c)*factor
    x = 2*(x0-interval[0])/(interval[1]-interval[0]) - 1
    
    if x==-1 and f0==None:
        ci[0] = -sum((-1)**r_[1:N+1]*ci[1:])
    else:
        ci[0] = f0 - clenshaw(x,ci)
    return ci



def cheb_convolve(a,b):
    '''Finds the product of two functions whose Chebyshev coefficients are 
    given by a and b. Output is the coefficiets of the product.'''

    M = len(b)
    N = len(a)
    
    if N>M:
        b = r_[b,zeros(N-M)]
        N = N - 1
    elif M>N:
        a = r_[a,zeros(M-N)]
        N = M - 1
    else:
        N = N - 1
    
    a[0] = a[0]*2.
    b[0] = b[0]*2.
        
    c0 = a[0]*b[0] + 2*dot(a[1:],b[1:])
    
    c1 = [ dot(a[0:k+1][::-1],b[0:k+1]) + dot(a[1:N-k+1],b[k+1:N+1]) + dot(a[k+1:N+1],b[1:N-k+1])  for k in range(1,N) ]

    c2 = [ dot(a[k-N:N+1][::-1],b[k-N:N+1])  for k in range(N,2*N+1)]
    
    c = r_[c0/2,c1,c2]/2.
    
    return c[:N+1]
    
def cosT(d,inverse=False):
    '''Finds the cosine transform of a given sequence'''
    b = []
    N = len(d)-1
    for n in r_[0:N+1]:
        b.append(sum(d*cos(n*r_[0:N+1]*pi/N)))
    b = array(b)
    if inverse:
        return b
    else:
        b[0] = b[0]/(N)
        b[1:] = b[1:]*2/(N)
        return b

In [57]:
def cintmatrix(N, interval=[-1,1]):
    A=np.eye(N)
    B=np.zeros((N,N))
    i=0
    for row in A:
        B[i,:]= chebI(chebI(row,interval,1,0),interval,-1,0)
        i+=1
    T=B.transpose() 
    return T

In [58]:
def loader(i,N):
    e = np.zeros(N)
    e[i] = 1
    j=np.empty((N,))
    j[::2]=1
    j[1::2]=-1
    p = chebI(chebI(e,[-1,1],-1,0),[-1,1],1,0)
    return dot(p,j)

In [59]:
e = np.zeros(N)
e[0] = 0.5
e[2] = 0.5
j=np.empty((N,))
j[::2]=1
j[1::2]=-1
p = chebI(chebI(e,[-1,1],-1,0),[-1,1],1,0)
p

array([-0.38541667,  0.33333333,  0.04166667,  0.        ,  0.01041667,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.  

In [60]:
N=10
i=1
e = np.zeros(N)
e[i] = 1
j=np.empty((N,))
j[::2]=1
j[1::2]=-1
s= chebI(e,[-1,1],-1,0)
r= chebI(s,[-1,1],1,0)
p = chebI(chebI(e,[-1,1],-1,0),[-1,1],1,0)
Int= cintmatrix(N)
Int

array([[-1.25      , -0.33333333,  0.47916667,  0.2       ,  0.05      ,
         0.04761905,  0.02589286,  0.02222222,  0.01785714,  0.06349206],
       [-1.        , -0.375     ,  0.33333333,  0.25      ,  0.06666667,
         0.04166667,  0.02857143,  0.02083333,  0.01587302,  0.0625    ],
       [ 0.25      ,  0.        , -0.16666667,  0.        ,  0.04166667,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.04166667,  0.        , -0.0625    ,  0.        ,
         0.02083333,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.02083333,  0.        , -0.03333333,
         0.        ,  0.0125    ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.0125    ,  0.        ,
        -0.02083333,  0.        ,  0.00833333,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.00833333,
         0.        , -0.01428571,  0.        

In [61]:
Int= cintmatrix(N)
Int

array([[-1.25      , -0.33333333,  0.47916667,  0.2       ,  0.05      ,
         0.04761905,  0.02589286,  0.02222222,  0.01785714,  0.06349206],
       [-1.        , -0.375     ,  0.33333333,  0.25      ,  0.06666667,
         0.04166667,  0.02857143,  0.02083333,  0.01587302,  0.0625    ],
       [ 0.25      ,  0.        , -0.16666667,  0.        ,  0.04166667,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.04166667,  0.        , -0.0625    ,  0.        ,
         0.02083333,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.02083333,  0.        , -0.03333333,
         0.        ,  0.0125    ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.0125    ,  0.        ,
        -0.02083333,  0.        ,  0.00833333,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.00833333,
         0.        , -0.01428571,  0.        

In [62]:
N=100
e = np.zeros(N)
e[1] = 1
e[0] =-1
I=np.identity(N)
B = np.zeros((N+1,N+1))
B[0:N,0:N]=I
B[0:N,-1]=e
B[-1,-1]=2
Int= cintmatrix(N)
A = np.zeros((N+1,N+1))
A[0:N,0:N]=Int
k = np.ones(N)
w= ones(N)
for i in range(N):
    w[i] = loader(i,1000) 
A[-1,0:N]=w
e= reshape(e, (N,1))
shape(e)
w= reshape(w,(1,N))
shape(w)
tild = 0.5*dot(e,w)
MatI= Int -tild

In [33]:
import scipy.linalg as lin

Method 1

In [63]:
lam1= lin.eigvals(A,B)
-1/lam1*pi**2/4

array([  1.05299610e+00+0.j,   3.35204551e+00+0.j,   2.67449138e+01+0.j,
         9.98562506e+01+0.j,   5.23059724e+01+0.j,   2.21628716e+02+0.j,
         1.49727546e+02+0.j,   3.92098595e+02+0.j,   2.95844515e+02+0.j,
         6.11270902e+02+0.j,   4.90664056e+02+0.j,   8.79146913e+02+0.j,
         7.34187469e+02+0.j,   1.19572707e+03+0.j,   1.02641513e+03+0.j,
         1.56101156e+03+0.j,   1.36734720e+03+0.j,   1.97500047e+03+0.j,
         1.75698373e+03+0.j,   2.43769384e+03+0.j,   2.19532475e+03+0.j,
         2.94909172e+03+0.j,   2.68237029e+03+0.j,   3.50919410e+03+0.j,
         3.21812036e+03+0.j,   4.11800100e+03+0.j,   3.80257495e+03+0.j,
         4.77551244e+03+0.j,   5.48172840e+03+0.j,   4.43573408e+03+0.j,
         6.23664890e+03+0.j,   5.11759775e+03+0.j,   7.04027394e+03+0.j,
         5.84816596e+03+0.j,   7.89260352e+03+0.j,   6.62743870e+03+0.j,
         8.79363764e+03+0.j,   7.45541600e+03+0.j,   9.74337630e+03+0.j,
         8.33209783e+03+0.j,   1.07418195e+04+0.j, 

Method 2

In [65]:
lam2= lin.eigvals(MatI)
-1/((lam2*pi**2)/4)

array([  1.72960628e-01-0.j,   4.39300496e+00-0.j,   1.64019599e+01-0.j,
         3.64037834e+01-0.j,   5.50592636e-01-0.j,   6.44044355e+01-0.j,
         8.59155495e+00-0.j,   1.00404740e+02-0.j,   2.45936053e+01-0.j,
         1.44404906e+02-0.j,   4.85941527e+01-0.j,   1.96405006e+02-0.j,
         2.56405071e+02-0.j,   8.05943759e+01-0.j,   3.24405116e+02-0.j,
         1.20594488e+02-0.j,   4.00405148e+02-0.j,   1.68594553e+02-0.j,
         4.84405172e+02-0.j,   2.24594593e+02-0.j,   5.76405190e+02-0.j,
         6.76405204e+02-0.j,   2.88594620e+02-0.j,   7.84405215e+02-0.j,
         3.60594639e+02-0.j,   4.40594653e+02-0.j,   9.00405224e+02-0.j,
         5.28594663e+02-0.j,   1.02440523e+03-0.j,   6.24594671e+02-0.j,
         1.15640524e+03-0.j,   1.29640524e+03-0.j,   7.28594678e+02-0.j,
         8.40594683e+02-0.j,   1.44440525e+03-0.j,   1.60040525e+03-0.j,
         9.60594687e+02-0.j,   1.08859469e+03-0.j,   1.76440525e+03-0.j,
         1.22459469e+03-0.j,   1.93640526e+03-0.j, 

### Mixed boundary conditons

$y''=\lambda y$

y'(-1)=0,y(1)=0

$y(x)= \int_{1}^{x}\int_{-1}^{s}y(p)dpds$


$\frac{1}{\lambda}y(x)= Iy$

In [66]:
lam3= lin.eigvals(Int)
-1/(lam3*pi**2/16)

array([  1.00000000e+00-0.j,   9.00000000e+00-0.j,   2.50000000e+01-0.j,
         4.90000000e+01-0.j,   8.10000000e+01-0.j,   1.21000000e+02-0.j,
         1.69000000e+02-0.j,   2.25000000e+02-0.j,   2.89000000e+02-0.j,
         3.61000000e+02-0.j,   4.41000000e+02-0.j,   5.29000000e+02-0.j,
         6.25000000e+02-0.j,   7.29000000e+02-0.j,   8.41000000e+02-0.j,
         9.61000000e+02-0.j,   1.08900000e+03-0.j,   1.22500000e+03-0.j,
         1.36900000e+03-0.j,   1.52100000e+03-0.j,   1.68100000e+03-0.j,
         1.84900000e+03-0.j,   2.02500000e+03-0.j,   2.20900000e+03-0.j,
         2.40100000e+03-0.j,   2.60100000e+03-0.j,   2.80900000e+03-0.j,
         3.02500000e+03-0.j,   3.24900000e+03-0.j,   3.48100000e+03-0.j,
         3.72100000e+03-0.j,   3.96900000e+03-0.j,   4.22500000e+03-0.j,
         4.48900000e+03-0.j,   4.76100000e+03-0.j,   5.04100000e+03-0.j,
         5.32900000e+03-0.j,   5.62500000e+03-0.j,   5.92900000e+03-0.j,
         6.24100000e+03-0.j,   6.56100000e+03-0.j, 

In [39]:
import scipy.linalg as p

In [21]:
lam= p.eigvals(A,B)

In [22]:
lam

array([ -7.36088195e-01+0.j        ,  -4.05284593e-01+0.j        ,
        -4.62180284e-02+0.00119322j,  -4.62180284e-02-0.00119322j,
        -1.86250177e-02+0.j        ,  -1.21091840e-02+0.j        ,
        -7.26829610e-03+0.00470714j,  -7.26829610e-03-0.00470714j,
         3.06970016e-03+0.j        ,   1.30155476e-16+0.j        ,
        -1.76783991e-03+0.j        ])

In [17]:
for i in range(1,20):
    l=1/(i)**2
    print(4*l/np.pi**2)

0.4052847345693511
0.10132118364233778
0.04503163717437234
0.025330295910584444
0.016211389382774045
0.011257909293593086
0.008271117032027573
0.006332573977646111
0.005003515241596927
0.004052847345693511
0.003349460616275629
0.0028144773233982714
0.002398134524079001
0.0020677792580068933
0.0018012654869748938
0.0015831434944115277
0.001402369323769381
0.0012508788103992319
0.0011226723949289503


In [18]:
1/lam

array([ -1.35853288e+00 -0.00000000e+00j,
        -2.46740110e+00 -0.00000000e+00j,
        -2.11988121e+01 -0.00000000e+00j,
        -2.22066099e+01 -0.00000000e+00j,
        -6.06822889e+01 -0.00000000e+00j,
        -6.16850275e+01 -0.00000000e+00j,
        -1.19901266e+02 -0.00000000e+00j,
        -1.20902654e+02 -0.00000000e+00j,
        -1.98858652e+02 -0.00000000e+00j,
        -1.99859489e+02 -0.00000000e+00j,
        -2.97554973e+02 -0.00000000e+00j,
        -2.98555533e+02 -0.00000000e+00j,
        -4.15990385e+02 -0.00000000e+00j,
        -4.16990786e+02 -0.00000000e+00j,
        -5.54164947e+02 -0.00000000e+00j,
        -5.55165248e+02 -0.00000000e+00j,
        -7.12078684e+02 -0.00000000e+00j,
        -7.13078918e+02 -0.00000000e+00j,
        -8.89731610e+02 -0.00000000e+00j,
        -8.90731797e+02 -0.00000000e+00j,
        -1.08712373e+03 -0.00000000e+00j,
        -1.08812389e+03 -0.00000000e+00j,
        -1.30425505e+03 -0.00000000e+00j,
        -1.30525518e+03 -0.0000000